-- 분류 정보 테이블(bookclass)
CREATE TABLE BOOKCLASS(
    cno NUMBER(4)
        CONSTRAINT BC_CNO_PK PRIMARY KEY,
    bclass VARCHAR2(15 CHAR)
        CONSTRAINT BC_BC_NN NOT NULL,
    sclass VARCHAR2(15 CHAR)
        CONSTRAINT BC_SC_NN NOT NULL
);

--도서 정보 테이블(book)

CREATE TABLE BOOKS(
    bno NUMBER(4)
        CONSTRAINT BK_BNO_PK PRIMARY KEY,
    cno NUMBER(4)
        CONSTRAINT BK_CNO_FK REFERENCES bookclass(cno)
        CONSTRAINT BK_CNO_NN NOT NULL,
    bname VARCHAR2(30 CHAR)
        CONSTRAINT BK_BNAME_NN NOT NULL,
    publisher VARCHAR2(15 CHAR)
        CONSTRAINT BK_PUBLISH_NN NOT NULL,
    writer VARCHAR2(15 CHAR)
        CONSTRAINT BK_WRITER_NN NOT NULL,
    trans VARCHAR2(15 CHAR),
    vers VARCHAR2(15 CHAR)
        CONSTRAINT BK_VERSION_NN NOT NULL,
    fdate DATE
        CONSTRAINT BK_FDATE_NN NOT NULL,
    ldate DATE
        CONSTRAINT BK_LDATE_NN NOT NULL,
    gdate DATE
        CONSTRAINT BK_GDATE_NN NOT NULL,
    isget CHAR(1) DEFAULT 'Y'
        CONSTRAINT MB_SHOW_CK CHECK(isget IN('Y', 'N'))
        CONSTRAINT MB_SHOW_NN NOT NULL
);

