GRANT SELECT ANY TABLE TO jennie;

CREATE USER githrd IDENTIFIED BY 12345 ACCOUNT UNLOCK;
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO githrd;
ALTER USER githrd DEFAULT TABLESPACE USERS;

drop user githrd cascade;